"""Add risk tolerance and goals

Revision ID: 6a5032d21f50
Revises: e8a2e26fb728
Create Date: 2025-05-05 16:52:45.022002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a5032d21f50'
down_revision = 'e8a2e26fb728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investment_strategy')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_tolerance', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('investment_goals', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('investment_goals')
        batch_op.drop_column('risk_tolerance')

    op.create_table('investment_strategy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('risk_profile', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('allocations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='investment_strategy_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='investment_strategy_pkey')
    )
    # ### end Alembic commands ###
